### ISSUE TITLE
Switch promises to bluebird

### ISSUE THREAD

**Issue by 00christian00** [tarantool/node-tarantool-driver#24]
It seem even in the latest version promises are still very slow : 
http://softwareengineering.stackexchange.com/questions/331991/are-native-promises-still-slower-in-node-vs-libraries-such-as-bluebird/331992#331992
How about switching to bluebird? 
Or allow an optional parameter so users can pass the module if they installed it:
something like : 
var P = Promise;
function TarantoolConnection (options){
    this.socket = new net.Socket({
        readable: true,
        writable: true
    });
..... etc
if(options.bluebird!==undefined) P=bluebird;

}

Then in the client code you would have something like:
var BlueB= require('bluebird');
var conn = new TarantoolConnection({
   bluebird:BlueB,
    host: 'localhost',
    port: 3301});

This way you can leave almost everything else same.

**Comment by KlonD90** [comment]
It's cool but in my tests it's not a really bottleneck. I have some troubles with a handling a lot of responses right now and search for some way to do it right. Iproto is not a pipelining protocol so server can send answer to my requests in any sequences.
