### ISSUE TITLE
v3.0 roadmap

### ISSUE THREAD

**Issue by noevents** [tarantool/node-tarantool-driver#30]
1. Code refactoring (ioredis used as reference)✔
2. Reconnection (ioredis used as reference)✔
3. Remove "auth" method from api (instant authentication when an instanse created)✔
4. "destroy" method refactoring (also renamed to "disconnect")✔
5. Self errors - TarantoolError constructor ✔
6. Add tests coverage tool (coveralls) ✔
7. Add missing test cases. ✔
8. Multihost support.  ✔

**Comment by noevents** [comment]
Complete readme.md, add new api.

**Comment by arusakov** [comment]
Why version 3 has not published yet?
