### ISSUE TITLE
Проблема с передачей типа number

### ISSUE THREAD

**Issue by ipfedor** [tarantool/node-tarantool-driver#32]
Описан индекс:
    users_space:create_index('expired', {
        if_not_exists = true,
        type = 'TREE',
        unique = false,
        parts = {24, 'unsigned'}
    })

Пытаюсь сохранить в поле содержимое date.getTime() (typeof выдает "number") ,  получаю ошибку несовпадения типов (тип должен быть unsigned).
Если сохранять значение без миллисекунд (делим на 1000), проблема исчезает.

**Comment by noevents** [comment]
@ipfedor 
Дело в том, что тип unsigned в tarantool соответствует типу uint в msgpack, который вмещает до 8 знаков. Так как  .getTime() возвращает число из 13 знаков, msgpack кодирует это число в тип double(float64), который соответствует number в tarantool.
[indexed-field-types](https://tarantool.org/en/doc/1.7/book/box/data_model.html?highlight=types#indexed-field-types)

**Comment by ipfedor** [comment]
ясно, спасибо
