### ISSUE TITLE
Упростить работу с операциями

### ISSUE THREAD

**Issue by monolithed** [tarantool/node-tarantool-driver#4]
В tarantool 1.6 [не требуется](https://blueprints.launchpad.net/tarantool/+spec/space-aliases) указывать _space_id_ 
См. аналог драйвера [tarantool-python](http://tarantool-python.readthedocs.org/en/latest/quick-start.en.html)

**Comment by KlonD90** [comment]
Да надо бы добавить это. Типа при передачи строки пытаться достать метаданные space'ов и самому запомнить space_id.
Займусь на неделе.

**Comment by KlonD90** [comment]
@monolithed 6ccbec1d908c47404736adab46f2b963f09821ce
resolve

**Comment by monolithed** [comment]
Вау, благодарю!

**Comment by monolithed** [comment]
C `select` что-то не так:

```js
tarantool.call('replace_batch', [
	[ 'yandex.ru', 'ru'],
	[ 'google.ru', ''en' ]
])

tarantool.select('yandex.ru', 'primary', 1, 0, ['ru']);
```

```
[ReferenceError: reject is not defined]
```

Или я что-то не так понял.

PS: почему бы не сделать что-то вроде:

``js
tarantool.select('yandex.ru');

tarantool.select(['yandex.ru', 'google.com']); // для составных ключей

tarantool.select(['yandex.ru'], 'secondary', { 
    iterator: 'GT', 
    limit: 1000
});
```

Собственно так сделано в [tarantool-python](http://tarantool-python.readthedocs.org/en/latest/quick-start.en.html)

**Comment by KlonD90** [comment]
Хорошо, попробую на следующий выходных подумать насчет того как удобнее использовать API.

**Comment by KlonD90** [comment]
@monolithed пока убрал key чтобы всегда был массивом если просто число то я оберну в тапл на стороне драйвера.
А вот прежде чем менять API я дозавершу performance, а уже потом выпущу тогда 1.0 версию с ломающими изменениями.
