### ISSUE TITLE
Баг в сборке логического пакета

### ISSUE THREAD

**Issue by tommiv** [tarantool/node-tarantool-driver#43]
Парни, смотрите, вот тут https://github.com/tarantool/node-tarantool-driver/blob/master/lib/parser.js#L50 у вас стоит loose проверка входящих аргументов. Если вот здесь https://github.com/tarantool/node-tarantool-driver/blob/master/lib/event-handler.js#L92 волею судеб в обработчик придет пакет данных длиной 5 байт, то `data.length - offset === 0`, и проверка `if (from && size)` не пройдет, в результате чего выполнится ветка `else`. Я не знаю, баг это или фича, но в таком варианте драйвер при `data.length === 5` портит буфер, сдвигая его на 5 байт, затем пытается считать `code`, который не на своем месте, и падает с неизвестной ошибкой. Замена этой строки на `if (from !== undefined && size !== undefined)` исправляет ситуацию. 

P.S.: Ошибка проявляется, если методично в цикле бомбить сервер операцией upsert. Смена задержки между итерациями и/или размера записываемых данных ни на что не влияет. А самое интересное, что падает все всегда на одной и той же итерации.

**Comment by KlonD90** [comment]
Спасибо. Зарелизил 3.0.2 с этим фиксом
