### ISSUE TITLE
Несовместимость с  tarantool:2.11, на запросы приходит ответ "undefined"

### ISSUE THREAD

**Issue by ngalkin91** [tarantool/node-tarantool-driver#52]
Столкнулся предположительно с несовместимостью драйвера с tarantool версий 2.11.* - на все запросы возвращается ответ undefined.

Шаги для воспроизведения:

1) создать packages.json:
```json
{
  "dependencies": {
    "tarantool-driver": "^3.0.6"
  }
}
```

2) создать index.js:
```javascript
const TarantoolConnection = require('tarantool-driver');

var conn = new TarantoolConnection({ host: '127.0.0.1', port: 3301 })

conn.eval('return 2 + 2').then(function (res) {
    console.log(res)
})
```

3) выполнить:
```console
npm i
```

4) выполнить `docker run --name tarantool -p 3301:3301 -d --rm tarantool/tarantool:2.11.3`

5) выполнить `node index.js`

6) **получаем ответ: undefined**

При этом если выполнять тот же самый код на старой версии, например tarantool/tarantool:1.10.15, то получаем корректный ответ: **[ 4 ]**

**Comment by Talkytitan5127** [comment]
when use credentials to connect to tarantool, conn.eval raise error
![image](https://github.com/tarantool/node-tarantool-driver/assets/22394485/6ffea239-a94c-47c3-8be7-b15247793ca2)

**Comment by sergos** [comment]
Have a try - pushed new fixup.

**Comment by ngalkin91** [comment]
> Have a try - pushed new fixup.

Now it works, thank you
